language: c

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      compiler: clang
    - os: linux
      dist: trusty
      compiler: gcc
    - os: linux
      dist: precise
      compiler: clang
    - os: linux
      dist: precise
      compiler: gcc

sudo: required

before_install:
  - sudo apt-get update --quiet --assume-yes
  - sudo apt-get install splint --quiet --assume-yes
  - sudo apt-get install valgrind --quiet --assume-yes

before_script: ./autogen.sh
script:
  - ./autogen.sh && ./configure --disable-shared
  - if [[ $(lsb_release -c -s) == "precise" ]]; then make ci; fi
  - if [[ $(lsb_release -c -s) == "trusty" ]];  then make ci;   fi
